name:                mock-typeable
version:             0.1.0.0
github:              "githubuser/mock-typeable"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mock-typeable#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- call-stack >= 0.2.0

default-extensions:
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- LambdaCase
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

ghc-options:
- -Wall
# - -Wno-missing-import-lists
# - -Wno-prepositive-qualified-module
# - -Wno-unsafe

library:
  source-dirs: src

tests:
  mock-typeable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mock-typeable
    - hspec
