name:                typeable-mock
version:             0.1.0.0
github:              "lykahb/typeable-mock"
license:             BSD3
author:              "Boris Lykah"
maintainer:          "lykahb@gmail.com"
copyright:           "2021 Boris Lykah"

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on GitHub at <https://github.com/lykahb/typeable-mock#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- call-stack >= 0.2.0

default-extensions:
- DerivingStrategies
- GADTs
- GeneralizedNewtypeDeriving
- LambdaCase
- RankNTypes
- FlexibleInstances
- MultiParamTypeClasses
- FunctionalDependencies
- RecordWildCards

ghc-options:
- -Wall
# - -Wno-missing-import-lists
# - -Wno-prepositive-qualified-module
# - -Wno-unsafe

library:
  source-dirs: src

tests:
  typeable-mock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typeable-mock
    - hspec
