name:                typeable-mock
version:             0.1.0.1
github:              "lykahb/typeable-mock"
license:             BSD3
author:              "Boris Lykah"
maintainer:          "lykahb@gmail.com"
copyright:           "2021 Boris Lykah"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Mock functions and expressions anywhere.
category:            Testing

description:         Please see the README on GitHub at <https://github.com/lykahb/typeable-mock#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- call-stack >= 0.2.0
- variadic-function >= 0.1.0.0 && < 0.2

default-extensions:
- FlexibleContexts
- GADTs
- LambdaCase
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- TypeOperators

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  typeable-mock-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typeable-mock
    - hspec
